services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    volumes:
      - /srv/dev-disk-by-uuid-${DRIVE_UUID}/Media/Config:/config
      - /srv/dev-disk-by-uuid-${DRIVE_UUID}/Media/Cache:/cache
      - /srv/dev-disk-by-uuid-C${DRIVE_UUID}:/data
    restart: unless-stopped
